### PR TITLE
Fix inconsistent result after apply errors for sftpgo_user resources

### LINKED ISSUE #13: Getting "Provider produced inconsistent result after apply for" sftpgo_user resource
Getting these errors after each `terraform apply` run, and terraform keeps trying to change my `sftpgo_user` resource aven after applying it.
```
sftpgo_user.ftpuser: Modifying... [id=ftpuser]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to sftpgo_user.ftpuser, provider "provider[\"registry.terraform.io/drakkan/sftpgo\"]" produced an unexpected new value:
│ .quota_size: was cty.NumberIntVal(0), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to sftpgo_user.ftpuser, provider "provider[\"registry.terraform.io/drakkan/sftpgo\"]" produced an unexpected new value:
│ .quota_files: was cty.NumberIntVal(0), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to sftpgo_user.ftpuser, provider "provider[\"registry.terraform.io/drakkan/sftpgo\"]" produced an unexpected new value:
│ .download_bandwidth: was cty.NumberIntVal(0), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to sftpgo_user.ftpuser, provider "provider[\"registry.terraform.io/drakkan/sftpgo\"]" produced an unexpected new value:
│ .max_sessions: was cty.NumberIntVal(0), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to sftpgo_user.ftpuser, provider "provider[\"registry.terraform.io/drakkan/sftpgo\"]" produced an unexpected new value:
│ .upload_bandwidth: was cty.NumberIntVal(0), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

image

### PR DESCRIPTION
**Pull request by cristim**
Fixes #13.

# Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://sftpgo.com/cla.html)?

---

### CODE REVIEW

**Comment by cristim** [comment]
After applying this change and configuring the provider override in `.terraformrc` the terraform apply converges to the expected configuration:

image

And also subsequent runs show no further changes are needed:
image

**Comment by cristim** [comment]
@drakkan thanks for your amazing work with SFTPGo!

**Comment by drakkan** [comment]
Thank you, but I would like to avoid a specific if for each nullable value. From the docs

Schermata del 2024-07-29 11-01-24

If you omit quota_size it should work with no code change

**Comment by cristim** [comment]
Thanks, I had all of them set to zero, which messed it up.

I deleted them from the configuration and it works as expected.

**Comment by drakkan** [comment]
Ideally it should work in both cases, but it's not easy - if we for example remove `omitempty` for non-string fields from SFTPGo models, then it would require setting those values ​​to 0. 

We would have to convert everything to pointers... but should we do that just to improve this provider and risk introducing nil pointer dereferences into SFTPGo?

**Pull request closed without merging**
